version: '3.5'

services:
    proxy:
        image: traefik:latest
        container_name: traefik_reverse_proxy
        command: 
            - "--log.level=ERROR"
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--entrypoints.web.address=:80"
        networks:
            - public
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: unless-stopped

networks:
    public:
        name: traefik_public
        driver: bridge

