version: '3.2'

services:
    proxy:
        image: traefik
        container_name: web-reverse-proxy
        command: --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
        networks:
            - public
        ports:
            - "80:80"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /dev/null:/traefik.toml
        restart: unless-stopped

networks:
    public:
        driver: bridge

